"""empty message

Revision ID: 1e349c42a7a8
Revises: 401810846220
Create Date: 2022-04-01 01:27:01.581247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e349c42a7a8'
down_revision = '401810846220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.Integer(), nullable=True),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groupname'], ['group.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user')
    # ### end Alembic commands ###
