"""empty message

Revision ID: 283962d42c16
Revises: 5dae22e695bc
Create Date: 2023-10-15 21:46:39.621374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283962d42c16'
down_revision = '5dae22e695bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'comment')
    # ### end Alembic commands ###
