"""empty message

Revision ID: 401810846220
Revises: 13c3d3f38a3c
Create Date: 2022-04-01 00:45:56.157779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401810846220'
down_revision = '13c3d3f38a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
