"""empty message

Revision ID: 5dae22e695bc
Revises: dfae9c3c0750
Create Date: 2023-10-15 21:41:40.082472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dae22e695bc'
down_revision = 'dfae9c3c0750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('comment', sa.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
