"""empty message

Revision ID: a4c1f76421bd
Revises: ec4481d20932
Create Date: 2023-05-17 17:41:47.696759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c1f76421bd'
down_revision = 'ec4481d20932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'teacher_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('teacher_name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
