"""empty message

Revision ID: ba70cd290304
Revises: ca0e8370d635
Create Date: 2023-06-16 01:27:21.912549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba70cd290304'
down_revision = 'ca0e8370d635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('var_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'var_name')
    # ### end Alembic commands ###
