"""empty message

Revision ID: ca0e8370d635
Revises: a4c1f76421bd
Create Date: 2023-05-17 17:41:56.597801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0e8370d635'
down_revision = 'a4c1f76421bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('teacher_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'teacher_name')
    # ### end Alembic commands ###
