"""empty message

Revision ID: d1fe9f04b148
Revises: 1e349c42a7a8
Create Date: 2022-04-01 02:01:32.882305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fe9f04b148'
down_revision = '1e349c42a7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('groupname', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.INTEGER(), nullable=True),
    sa.Column('groupid', sa.INTEGER(), nullable=True),
    sa.Column('userid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['groupname'], ['group.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
