"""empty message

Revision ID: dfae9c3c0750
Revises: ba70cd290304
Create Date: 2023-08-01 16:54:10.686933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfae9c3c0750'
down_revision = 'ba70cd290304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('task_file', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'task_file')
    # ### end Alembic commands ###
