"""empty message

Revision ID: e9e9d6bc787c
Revises: cc9a09893ba1
Create Date: 2023-04-07 16:49:02.207251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e9d6bc787c'
down_revision = 'cc9a09893ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'var_folder')
    op.drop_column('user', 'var_folder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('var_folder', sa.VARCHAR(length=128), nullable=True))
    op.add_column('report', sa.Column('var_folder', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
