"""empty message

Revision ID: f9f09f5f779f
Revises: e9e9d6bc787c
Create Date: 2023-04-07 16:49:46.707614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f09f5f779f'
down_revision = 'e9e9d6bc787c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('var_file', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('var_file', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'var_file')
    op.drop_column('report', 'var_file')
    # ### end Alembic commands ###
